server.port=${PORT:8761}

eureka.instance.hostname=${EUREKA_HOSTNAME}
eureka.instance.prefer-ip-address=false

# Force Eureka to use the public hostname
eureka.instance.instance-id=${EUREKA_HOSTNAME}

eureka.instance.home-page-url=https://${EUREKA_HOSTNAME}
eureka.instance.status-page-url=https://${EUREKA_HOSTNAME}/actuator/info
eureka.instance.health-check-url=https://${EUREKA_HOSTNAME}/actuator/health

eureka.instance.non-secure-port-enabled=false
eureka.instance.secure-port-enabled=true
eureka.instance.secure-port=443