server.port=${PORT:8761}

eureka.instance.hostname=${EUREKA_HOSTNAME}
eureka.instance.prefer-ip-address=false

eureka.instance.home-page-url=https://${EUREKA_HOSTNAME}
eureka.instance.status-page-url=https://${EUREKA_HOSTNAME}/actuator/info
eureka.instance.health-check-url=https://${EUREKA_HOSTNAME}/actuator/health